services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-3.9.14}-management
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
        interval: 3s
        timeout: 3s
        retries: 5
    ports:
      - 5672:5672
      - 15672:15672